version: '3.8'

services:
  redis:
    image: redis:5-buster
    container_name: redis
    ports:
      - '6379:6379'
    restart: always
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 30s
      timeout: 10s
      retries: 5
    logging:
      driver: 'json-file'
      options:
        max-size: '200k'
        max-file: '3'
    networks:
      - aptoso_network

  nest-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-app
    ports:
      - '3333:3333'
    depends_on:
      - redis
      # - mongodb
    env_file:
      - .env.docker
    restart: always
    networks:
      - aptoso_network

networks:
  aptoso_network:
    driver: bridge
# volumes:
#   mongo_data:
